[build]
  command = "npm run build:prod"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=./" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200